steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/whartbar/abc', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/whartbar/abc']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'abc', '--image', 'gcr.io/whartbar/abc', '--region', 'us-central1','--platform', 'managed', '--quiet', '--allow-unauthenticated']
images:
- gcr.io/whartbar/abc