steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/whartbar/whitehartweb', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/whartbar/whitehartweb']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cdservice', '--image', 'gcr.io/whartbar/whitehartweb', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
- gcr.io/whartbar/whitehartweb
